<a href="https://colab.research.google.com/github/20201356/Stats_spr2025/blob/main/6_Read_Write_Files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Read files in various formats**

- <font color = 'red'> read_FILEFORMAT()fuction
  - csv
  - json
  - html
  - clipboard
  - excel
  - hdf
  - sql

###**Write files in various formats**
- <font color = 'blue'> 00.to_FILEFORMAT("")method
  - csv
  - json
  - html
  - clipboard
  - excel
  - hdf
  - sql

pp.058-062 (cf., 옵션 설명 표는 책 참조)

[공공데이터포털](https://www.data.go.kr/)
- csv, xlxs 등의 자료를 다운로드 받을 수 있는 대한민국 공식 전자정부 누리집

#🐹🐾**Reading data**

In [5]:
!git clone 'https://github.com/ms624atyale/Pandas_Stats_Data_Analysis_2025'

Cloning into 'Pandas_Stats_Data_Analysis_2025'...
remote: Enumerating objects: 387, done.
remote: Counting objects: 100% (247/247), done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 387 (delta 126), reused 110 (delta 53), pack-reused 140 (from 1)
Receiving objects: 100% (387/387), 3.26 MiB | 23.83 MiB/s, done.
Resolving deltas: 100% (209/209), done.

###**<font color = 'red'> 🐹🐾 Read the csv format**

In [9]:
# csv (comma separated values) format

import pandas as pd

#file directory
file = "/content/sample_data/sample.csv"

#read_csv() function으ㄹ 사용하여 데이터프레임 변환, 기본값 0행을 열 지정 (열지정이 뭐야??)
df1 = pd.read_csv(file)
print(df1)
print('\n')

#header = None 선택
df2 = pd.read_csv(file, header = None)
print(df2)
print('\n')

#hearder = 1 선택
df3 = pd.read_csv(file, header = 1)
print(df3)
print('\n')

#index_col = False (인덱스 지정하지 않음)
df4 = pd.read_csv(file, index_col = False)
print(df4)
print('\n')

#index_col = 'c0' 첫 번째 열을 인덱스 지정
df5 = pd.read_csv(file, index_col = 'c0')
print(df5)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/sample.csv'

In [17]:
import pandas as pd

file = "/content/KINTEX시설현황.csv"

# 기본 출력
df1 = pd.read_csv(file)
print(df1)
print('\n')

# 헤더 없음 처리
df2 = pd.read_csv(file, header=None)
print("df2:")
print(df2)
print('\n')

# 두 번째 줄을 헤더로 사용
df3 = pd.read_csv(file, header=1)
print("df3:")
print(df3)
print('\n')

# 인덱스를 따로 지정하지 않음
df4 = pd.read_csv(file, index_col=False)
print("df4:")
print(df4)
print('\n')

# 실제 컬럼명을 확인 후 index_col 지정
print("컬럼명 확인:", df1.columns.tolist())

# 예: 첫 번째 컬럼을 인덱스로 사용하고 싶다면
df5 = pd.read_csv(file, index_col=0)
print("df5:")
print(df5)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte

###**<font color = 'red'> 🐹🐾 Read the excel format**
- use element (engine = 'openpyxl') for .xlxs
- use element (engine = 'xlrd') for .xls

In [ ]:
import pandas as pd
df1 = pd.read_excel("/content/sample_data/남북한발전전력량.xlsx", engine = 'openpyxl') #header = 0 (by default)
df2 = pd.read_excel("/content/sample_data/남북한발전전력량.xlsx", engine = 'openpyxl', header = None) #header unapplied

print(df1)
print('\n')
print(df2)

  전력량 (억㎾h) 발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...  2007  \
0        남한     합계  1077  1186  1310  1444  1650  1847  2055  2244  ...  4031
1       NaN     수력    64    51    49    60    41    55    52    54  ...    50
2       NaN     화력   484   573   696   803  1022  1122  1264  1420  ...  2551
3       NaN    원자력   529   563   565   581   587   670   739   771  ...  1429
4       NaN    신재생     -     -     -     -     -     -     -     -  ...     -
5        북한     합계   277   263   247   221   231   230   213   193  ...   236
6       NaN     수력   156   150   142   133   138   142   125   107  ...   133
7       NaN     화력   121   113   105    88    93    88    88    86  ...   103
8       NaN    원자력     -     -     -     -     -     -     -     -  ...     -

   2008  2009  2010  2011  2012  2013  2014  2015  2016
0  4224  4336  4747  4969  5096  5171  5220  5281  5404
1    56    56    65    78    77    84    78    58    66
2  2658  2802  3196  3343  3430  3581  3427  3402  3523
3  1510  1478  1486  1547  1503  1388  1564  1648  1620
4     -     -     -     -    86   118   151   173   195
5   255   235   237   211   215   221   216   190   239
6   141   125   134   132   135   139   130   100   128
7   114   110   103    79    80    82    86    90   111
8     -     -     -     -     -     -     -     -     -

[9 rows x 29 columns]


          0       1     2     3     4     5     6     7     8     9   ...  \
0  전력량 (억㎾h)  발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...
1         남한      합계  1077  1186  1310  1444  1650  1847  2055  2244  ...
2        NaN      수력    64    51    49    60    41    55    52    54  ...
3        NaN      화력   484   573   696   803  1022  1122  1264  1420  ...
4        NaN     원자력   529   563   565   581   587   670   739   771  ...
5        NaN     신재생     -     -     -     -     -     -     -     -  ...
6         북한      합계   277   263   247   221   231   230   213   193  ...
7        NaN      수력   156   150   142   133   138   142   125   107  ...
8        NaN      화력   121   113   105    88    93    88    88    86  ...
9        NaN     원자력     -     -     -     -     -     -     -     -  ...

     19    20    21    22    23    24    25    26    27    28
0  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016
1  4031  4224  4336  4747  4969  5096  5171  5220  5281  5404
2    50    56    56    65    78    77    84    78    58    66
3  2551  2658  2802  3196  3343  3430  3581  3427  3402  3523
4  1429  1510  1478  1486  1547  1503  1388  1564  1648  1620
5     -     -     -     -     -    86   118   151   173   195
6   236   255   235   237   211   215   221   216   190   239
7   133   141   125   134   132   135   139   130   100   128
8   103   114   110   103    79    80    82    86    90   111
9     -     -     -     -     -     -     -     -     -     -

[10 rows x 29 columns]

In [21]:
import pandas as pd
df1 = pd.read_excel("/content/남북한발전전력량.xlsx", engine = 'openpyxl') #header = 0 (by default)
df2 = pd.read_excel("/content/남북한발전전력량.xlsx", engine = 'openpyxl', header = None) #header unapplied

print(df1)
print('\n')
print(df2)

  전력량 (억㎾h) 발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...  2007  \
0        남한     합계  1077  1186  1310  1444  1650  1847  2055  2244  ...  4031
1       NaN     수력    64    51    49    60    41    55    52    54  ...    50
2       NaN     화력   484   573   696   803  1022  1122  1264  1420  ...  2551
3       NaN    원자력   529   563   565   581   587   670   739   771  ...  1429
4       NaN    신재생     -     -     -     -     -     -     -     -  ...     -
5        북한     합계   277   263   247   221   231   230   213   193  ...   236
6       NaN     수력   156   150   142   133   138   142   125   107  ...   133
7       NaN     화력   121   113   105    88    93    88    88    86  ...   103
8       NaN    원자력     -     -     -     -     -     -     -     -  ...     -

   2008  2009  2010  2011  2012  2013  2014  2015  2016
0  4224  4336  4747  4969  5096  5171  5220  5281  5404
1    56    56    65    78    77    84    78    58    66
2  2658  2802  3196  3343  3430  3581  3427  3402  3523
3  1510  1478  1486  1547  1503  1388  1564  1648  1620
4     -     -     -     -    86   118   151   173   195
5   255   235   237   211   215   221   216   190   239
6   141   125   134   132   135   139   130   100   128
7   114   110   103    79    80    82    86    90   111
8     -     -     -     -     -     -     -     -     -

[9 rows x 29 columns]


          0       1     2     3     4     5     6     7     8     9   ...  \
0  전력량 (억㎾h)  발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...
1         남한      합계  1077  1186  1310  1444  1650  1847  2055  2244  ...
2        NaN      수력    64    51    49    60    41    55    52    54  ...
3        NaN      화력   484   573   696   803  1022  1122  1264  1420  ...
4        NaN     원자력   529   563   565   581   587   670   739   771  ...
5        NaN     신재생     -     -     -     -     -     -     -     -  ...
6         북한      합계   277   263   247   221   231   230   213   193  ...
7        NaN      수력   156   150   142   133   138   142   125   107  ...
8        NaN      화력   121   113   105    88    93    88    88    86  ...
9        NaN     원자력     -     -     -     -     -     -     -     -  ...

     19    20    21    22    23    24    25    26    27    28
0  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016
1  4031  4224  4336  4747  4969  5096  5171  5220  5281  5404
2    50    56    56    65    78    77    84    78    58    66
3  2551  2658  2802  3196  3343  3430  3581  3427  3402  3523
4  1429  1510  1478  1486  1547  1503  1388  1564  1648  1620
5     -     -     -     -     -    86   118   151   173   195
6   236   255   235   237   211   215   221   216   190   239
7   133   141   125   134   132   135   139   130   100   128
8   103   114   110   103    79    80    82    86    90   111
9     -     -     -     -     -     -     -     -     -     -

[10 rows x 29 columns]

In [22]:
# pandas DataFrame을 HTML 표로 변환
html_table_df1 = df1.to_html(index=False)  # 인덱스 제외
html_table_df2 = df2.to_html(index=False)

# 결과 출력 (Jupyter에서 실행 시 표 형태로 보임)
from IPython.core.display import display, HTML

display(HTML("<h3>Header 적용된 표 (df1)</h3>" + html_table_df1))
display(HTML("<h3>Header 미적용 표 (df2)</h3>" + html_table_df2))

###**<font color = 'red'> 🐹🐾 Read the html format**
- visit a webpage.
 - e.g., google.com ➡️ hold <CONTROL> + Click ➡️ save as <Google> with the format of <Webpage, HTML Only> ➡️ hit Upload ➡️ select the <Google.html>
>
- [정보문화사 파이썬 머신러닝 판다스 데이터 분석](http://www.infopub.co.kr/new/include/detail.asp?sku=05000266) ➡️ 샘플자료 다운로드 (우측 하단)

In [ ]:
import pandas as pd

url = "/content/sample_data/sample.html"

#html 웹페이지의 표를 가져와서 데이터프레임으로 변환
tables = pd.read_html(url)

#표 개수 확인
print(len(tables))
print('\n')

#표 리스트의 원소를 반복하면서 (interating the element of the table list) 화면 출력
for i in range(len(tables)):
  print("tables[%s]" %i)
  print(tables[i])
  print('\n')

#파이썬 패키지 정보가 들어 있는 두 번째 데이터프레임을 선택하여 df 변수에 저장
df = tables[i]

#name 열을 인덱스로 저장
df.set_index(['name'], inplace = True)
print(df)

2


tables[0]
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9


tables[1]
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True


            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

#🐹🐾**Saving data**

In [29]:
import pandas as pd

url = "/content/sample_data/sample.html"

# HTML 파일에서 모든 표를 읽어와 리스트로 저장
tables = pd.read_html(url)

# 표 개수 출력
print(f"표 개수: {len(tables)}\n")

# 모든 표를 출력
for i, table in enumerate(tables):
    print(f"tables[{i}]")
    print(table)
    print('\n')

# 두 번째 표를 df에 저장 (인덱스는 1부터 시작)
if len(tables) >= 2:
    df = tables[1]

    # 'name' 열을 인덱스로 설정
    if 'name' in df.columns:
        df.set_index('name', inplace=True)
        print("=== 'name' 열을 인덱스로 설정한 데이터프레임 ===")
        print(df)
    else:
        print("'name' 열이 존재하지 않습니다.")
else:
    print("두 번째 표가 없습니다.")

<ipython-input-29-f1c48a49f846>:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(url)

ValueError: No tables found

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

###🐹🐾<font color = 'blue'> **Write as the csv format**

In [ ]:
#saving as csv format

import pandas as pd

#판다스 DataFrame()함수로 데이터프레임 변환한 것을 변수로 할당

data = {'name': ['Emma', "Sean", "Witney"],
        'algol': ['A', 'A+', 'B'],
        'basic': ['C', 'B', 'B+'],
        'c++': ['B+','C', 'C+'],
}
df = pd.DataFrame(data)
df.set_index('name', inplace=True) #name 열을 인덱스로 지정
#df.set_index('c++', inplace=True) #c++ 열을 인덱스로 지정
print(df)

df.to_csv("./df_sample.csv") #csv file saved in the <sample_data> directory of Colab

       algol basic c++
name
Emma       A     C  B+
Sean      A+     B   C
Witney     B    B+  C+

###🐹🐾<font color = 'blue'> **Write as the excel format**

In [ ]:
import pandas as pd

#data변수에 사전형 데이터로 자료를 정리
data = {'name': ['Emily', 'Andy', 'John'],
        'c++':['A', 'A+', 'B'],
        'basic': ['C', 'B', 'B+'],
        'JAVA': ['B+', 'C', 'C+']
        }

#Pandas DataFrame()function을 사용하여 데이터프레임 변환하여 이를 df 변수에 할당
df = pd.DataFrame(data)
df.set_index('name', inplace=True)
print(df)

df.to_excel('./df_sample.xlsx')

      c++ basic JAVA
name
Emily   A     C   B+
Andy   A+     B    C
John    B    B+   C+

###🐹🐾<font color = 'blue'> **Write as the excel format after combining multiple data frames**

In [ ]:
#여러개의 excel 파일을 파일 하나로 저장하기

import pandas as pd

data1 = {'name': ['Emily', 'Andy', 'John'],
        'c++':['A', 'A+', 'B'],
        'basic': ['C', 'B', 'B+'],
        'JAVA': ['B+', 'C', 'C+']
        }

data2 = {'c0':[1,2,3],
         'c1':[4,5,6],
         'c2':[7,8,9],
         'c3':[10,11,12],
         'c4':[13,14,15]
         }

df1=pd.DataFrame(data1)
df1.set_index('name', inplace=True)
print(df1)
print('\n')

df2=pd.DataFrame(data2)
df2.set_index('c0', inplace=True)
print(df2)

#df1을 sheet1으로, df2를 sheet2로 저장. 파일명은 df_excelwriter.xlsx 로 해본다.

writer = pd.ExcelWriter("./df_excelwriter.xlsx")

df1.to_excel(writer, sheet_name = 'grading')
df2.to_excel(writer, sheet_name='numbers')
writer.close() #To address this, you can use the writer.close() method instead of save(). This will properly close the Excel file and ensure that all the data is saved.

      c++ basic JAVA
name
Emily   A     C   B+
Andy   A+     B    C
John    B    B+   C+


    c1  c2  c3  c4
c0
1    4   7  10  13
2    5   8  11  14
3    6   9  12  15